// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMco4keu7QpLbWnVD46ElH5NP12WOMhA',
    appId: '1:681051309363:web:22f6cdc0c0771ec7c8ea46',
    messagingSenderId: '681051309363',
    projectId: 'smarthomme-connect',
    authDomain: 'smarthomme-connect.firebaseapp.com',
    storageBucket: 'smarthomme-connect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVC1z2pFy6hFoEpoLGMui0VAO40m-0t2w',
    appId: '1:681051309363:android:b7a693075593f47ec8ea46',
    messagingSenderId: '681051309363',
    projectId: 'smarthomme-connect',
    storageBucket: 'smarthomme-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3yzaLugWJxl4QXUKNGch7opdAgshCO6w',
    appId: '1:681051309363:ios:8731c0f478d6f36ec8ea46',
    messagingSenderId: '681051309363',
    projectId: 'smarthomme-connect',
    storageBucket: 'smarthomme-connect.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3yzaLugWJxl4QXUKNGch7opdAgshCO6w',
    appId: '1:681051309363:ios:8731c0f478d6f36ec8ea46',
    messagingSenderId: '681051309363',
    projectId: 'smarthomme-connect',
    storageBucket: 'smarthomme-connect.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUMco4keu7QpLbWnVD46ElH5NP12WOMhA',
    appId: '1:681051309363:web:d79010705502f5c6c8ea46',
    messagingSenderId: '681051309363',
    projectId: 'smarthomme-connect',
    authDomain: 'smarthomme-connect.firebaseapp.com',
    storageBucket: 'smarthomme-connect.firebasestorage.app',
  );
}
